name: ❓ Question / Help
description: Ask a question or get help with Moltzer
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reaching out! We're here to help. Please describe your question below.

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: "How do I...?"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Any additional context that might help us understand your question
      placeholder: "I'm trying to... but I'm not sure how to..."
    validations:
      required: false

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What platform are you using?
      options:
        - Windows
        - macOS
        - Linux
        - Not platform-specific
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Moltzer Version (if relevant)
      description: What version of Moltzer are you using? (Help → About)
      placeholder: "1.0.0"
    validations:
      required: false

  - type: textarea
    id: tried
    attributes:
      label: What Have You Tried?
      description: Have you already tried anything to solve this?
    validations:
      required: false
